version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: swistack
      POSTGRES_USER: swistack
      POSTGRES_PASSWORD: swistack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swistack-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - swistack-network

volumes:
  postgres_data:
  redis_data:

networks:
  swistack-network:
    driver: bridge